- internal/report/writer.go
- internal/report/writer_test.go
Fixes #4 
Signed-off-by: Vincent Desjardins <vdesjardins@gmail.com>
> fix writes when string longer than report width.

- internal/linter/pod.go
> linter: secret name

- k8s/popeye/cronjob.yml
> update cronjob manifest for correct image

- README.md
- pkg/popeye.go
which looks up ENV "POPEYE_DUMP_DIR"
or fallback to default behaviour
> add dumpDir function

- internal/report/writer.go
Fixes issue #70 by initializing keys with 0 length.
> Fixes #70 - Messages displayed five times

- internal/issues/codes.go
- internal/issues/codes_test.go
- internal/sanitize/svc.go
- internal/sanitize/svc_test.go
Add an error code for this sanitizer report + unit tests
> Fix bug #78

- README.md
While reading into the docs and the README, I found some minor typos and improved legibility/understandability in some places.
> docs: Update README, improve legibility, fix minor typos.

- README.md
- spinach/spinach_aks.yml
Added an example for Azure AKS Kubernetes clusters
> Initial add of an Azure AKS spinach file

- README.md
pretty sure this is a typo, but the formatting looked better when it was wrong. maybe need to fix the image?
> fix img height attribute typo

- README.md
change set to rback yaml the "---" betwen Service account and the cluster role and set net the new image to the CJ yamls
> Update Readme.md update the image version

- pkg/popeye.go
- pkg/popeye_test.go
Allows for specifying s3 buckets in the format `s3://bucket/key` or `bucket/path/to/key`
> Add support for uploading to S3 directories

- README.md
> Update README with S3 subdirectory instructions

- go.mod
- pkg/popeye.go
Fixes #141
Adding the `--save` flag works, I have not tested if saving to S3 works
> Write Prometheus output to file

- README.md
- docs/codes.md
Fixes #110. It contains the full list of codes. There is no further info, yet.
Also, I've noticed code 502 is apparently missing in the code...
> Adds Popeye codes list

- spinach/spinach_metakube.yml
This update excludes resources in namespaces that are managed by SysEleven.
> Update MetaKube spinach file

- docs/codes.md
https://github.com/derailed/popeye/issues/193
This PR resolves the issue I raised and also applies some basic prettier formatting for that md file.
If you don't want the formatting I can revert it back to what it was 😊
> corrected typo in docs/codes.md and applied prettier formatting

- docs/codes.md
- internal/issues/assets/codes.yml
Updated some confusing documentation to clarify what is actually being checked.
> POP-1109 Documentation Clarification

- README.md
> optimize README documents

- Makefile
- change_logs/release_v0.11.1.md
- cmd/root.go
- internal/cache/pdb.go
- internal/dag/pdb.go
- internal/sanitize/pdb.go
- internal/sanitize/pdb_test.go
- internal/sanitize/pod.go
- internal/sanitize/pod_test.go
- pkg/popeye.go
* [Issue #245](https://github.com/derailed/popeye/issues/245) Checking Kubernetes clusters fails because v1/PodSecurityPolicy is checked
* [PR #247](https://github.com/derailed/popeye/pull/247) Fix deprecated cronjob api
> Release v0.11.1

- README.md
> Fix README fred* namespaces exclusion

- internal/issues/issue.go
> Fix incorrect spelling

- Makefile
- change_logs/release_v0.11.3.md
- pkg/config/config.go
- pkg/config/config_test.go
> Release v0.11.3

- docs/codes.md
This PR updates the codes.md document to add missing code POP-113, POP-209.
Related issue: https://github.com/derailed/popeye/issues/273
> Add missing code POP-113, POP-209 to codes.md

- Makefile
- change_logs/release_v0.20.1.md
- internal/dag/cluster.go
- internal/scrub/cluster.go
- pkg/popeye.go
Patch release to debug cluster connection issue.
> Release v0.20.1

- Makefile
- change_logs/release_v0.20.2.md
- cmd/root.go
- internal/cache/cluster.go
- internal/cache/cluster_test.go
- internal/dag/cluster.go
- internal/dag/helper_test.go
- internal/dag/helpers.go
- internal/lint/cluster.go
- internal/lint/cluster_test.go
- internal/lint/ns.go
- internal/report/builder.go
- pkg/helpers.go
- pkg/popeye.go
---
. [#280](https://github.com/derailed/popeye/issues/280) No RunInfo in context
> Release v0.20.2

- Makefile
- README.md
- change_logs/release_v0.20.3.md
- internal/db/db.go
- internal/lint/cronjob.go
- internal/lint/gw.go
. [#284](https://github.com/derailed/popeye/issues/284) Db get failed for ""
> Popeye/release v0.20.3

- Makefile
- change_logs/release_v0.20.4.md
- internal/db/db.go
. [#286](https://github.com/derailed/popeye/issues/286) Boom! runtime error: invalid memory address or nil pointer dereference (see logs)
> Release v0.20.4

- .gitignore
- .goreleaser.yml
- .krew.yaml
- Makefile
- change_logs/release_v0.21.1.md
- internal/cilium/lint/cid.go
- internal/cilium/lint/cid_test.go
- internal/lint/svc.go
. [#296](https://github.com/derailed/popeye/issues/296) False positive: Single endpoint is associated with this service
> Popeye v0.21.1

- Makefile
- README.md
- change_logs/release_v0.21.2.md
- internal/dao/ev.go
- internal/issues/assets/codes.yaml
- internal/issues/codes_test.go
- internal/issues/collector.go
- internal/lint/cronjob.go
- internal/lint/dp_test.go
- internal/lint/ing_test.go
- internal/lint/job.go
. [#298](https://github.com/derailed/popeye/issues/298) Popeye showing errors for Complete cronjobs
> Popeye v0.21.2

- grafana/popeye-dashboard.json
Grafana dashboard improvements:
- fix datasource/dashboard name
- fix some queries
- add link to error codes documentation
> Update Grafana dashboard

- Makefile
- README.md
- change_logs/release_v0.22.1.md
- go.mod
- pkg/config/s3.go
- pkg/config/s3_test.go
* [#425](https://github.com/derailed/popeye/issues/425) Upload to s3 failing in v0.22.0
> Rel v0.22.1

- README.md
Small change to have the wording in the comment on line 129 to match that on line 120.
> Update "The Command Line" README.md section for consistency
