derailed/popeye

- README.md
- internal/linter/container.go
Tiny commit, fixed typos:
spinchyaml -> spinachyaml
unamed -> unnamed
> Fixed typos

- internal/k8s/client.go
- internal/linter/svc.go
This change moves the decision to error on missing endpoints/pods for a
service from k8s/client.go to linter/svc.go. In the cases where the svc
has no ClusterIP (where it is explicitly None, or not allowed such as
in the ExternalName svc type) we'll skip the check for Endpoints.
> Corrects ExternalName-typed services reporting missing Endpoints

- internal/report/tally.go
Thanks for adding Jurassic Mode in v0.2.0 - it definitely makes the output much more readable on terminals with limited character support.
I noticed however that I was still getting a replacement character box in the header tally where a percentage sign should have been, as seen below. It looks like a ٪ (ARABIC PERCENT SIGN) is used instead of an ASCII percentage, and hence can't be displayed on terminals with limited character support - such as Powershell's default configuration.
This PR changes the string formatting for the header tally to use an ASCII percentage if Jurassic Mode is enabled. This then displays as expected on my terminal with Jurassic Mode enabled;
This is the first time i've written anything in Go so hopefully i've done this correctly - i'm open to feedback if there's a …
> Use ASCII percentage symbol in Jurassic Mode

- pkg/popeye.go
This is obvious typo - Service linter was used to lint Secrets.
> Use Secret linter for secrets

- README.md
AFAIK this application works perfectly analyzing k8s clusters without metrics-server.
> Remove metrics server dependency in README

- assets/codes.yml
- internal/issues/codes.go
- internal/report/assets/r1.yml
- internal/report/assets/r2.yml
It stated that containers are running as root, but actually they
just CAN run as root (not enforced by securityContext)
> Improve message for code 302

- internal/cache/psp.go
- internal/dag/psp.go
- internal/sanitize/psp.go
- internal/sanitize/psp_test.go
PodSecurityPolicy apiVersion extensions/v1beta1 has been removed in k8s
1.16
> Updating PSP to use policy/v1beta1 instead of extensions/v1beta1

- internal/cache/ing.go
- internal/cache/ing_test.go
- internal/report/human.go
- internal/report/human_test.go
- internal/sanitize/sa_test.go
- internal/sanitize/secret.go
- internal/sanitize/secret_test.go
- internal/scrub/sa.go
- internal/scrub/sec.go
Currently, when running Popeye, I get the issue that certain Secrets are not referenced by other resources but in reality, they are being used by Ingresses.
This Pull Request tracks Secrets used by Ingress and improves the inflection for pluralized words in the report for humans.
> Track Secrets used by Ingresses

- internal/sanitize/crb.go
- internal/sanitize/crb_test.go
- internal/sanitize/rb.go
- internal/sanitize/rb_test.go
Hi, checking my cluster I see the following behaviour:
```
ROLES (2 SCANNED)                                                            💥 0 😱 0 🔊 0 ✅ 2 100٪
┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅
· logging/elasticsearch-master...................................................................✅
· logging/logstash-logstash......................................................................✅
ROLEBINDINGS (2 SCANNED)                                                       💥 0 😱 2 🔊 0 ✅ 0 0٪
┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅
· logging/elasticsearch-master...................................................................😱
😱 [POP-1300] References a Role …
```
> Cannot find a valid Role name referenced by a RoleBinding

- internal/report/writer.go
This will help with #73.
Even though tests currently do not break we should make sure it stays like this.
There are hard coded title separator in builder_test.go and writer_test.go.
> Add even less fanciness for jurassic output

- cmd/root.go
- internal/k8s/client.go
- pkg/config/flags.go
- pkg/popeye.go
- Currently, running popeye as a CronJob on K8s saves the filename as `sanitizer_n/a_<timestamp>.txt`
This is due to an [issue](https://github.com/kubernetes/kubernetes/issues/44954) in Kubernetes where API Server does not return the cluster name. 
This PR adds an option to provide the filename like shown below:
```
go run main.go --k8s-popeye-cluster-name abcd
Sanitizer saved to: sanitizer_abcd_1581462176820331000.txt
```
- Also added log message to AWS config in case of failure, as it currently does not show any reason.
```
go run main.go --s3-bucket xxxx --k8s-popeye-cluster-name abcd
Sanitizer saved to: sanitizer_abcd_1581462408819395000.txt
2020/02/11 15:06:51 DEBUG: Validate Request s3/PutObject failed, not retrying, error MissingRegion: could not find region configuration …
```
> Added option to provide filename

- README.md
The pipeline already builds the docker image for people to download.  Include an example of how users can use the docker image directly to run scans against your own clusters without having to build or install binaries.
> Add example of using popeye docker image directly

- spinach/spinach_metakube.yml
This PR adds a spinach file that rates a freshly provisioned cluster in [SysEleven MetaKube](https://www.syseleven.de/en/products-services/kubernetes) with 100 points.
> feat: add default spinach file for SysEleven MetaKube

- README.md
According to https://en.wikipedia.org/wiki/ANSI_escape_code, ANSI escape codes became a thing in 1979 😄
> 1989 => 1979 (ANSI escape codes were born then)

- README.md
- cmd/root.go
- pkg/config/flags.go
- pkg/popeye.go
Hi !
First, thanks for the great project :)
In my case, I wanted to generate Popeye HTML report file regularly (in a K8S deployment with 2 containers : a first launched from popeye image generates the report in a shared volume and the second one is a nginx container that will server the report as a static page). To achieve this easily, I found it would be convenient to specify the name of the report file because it would allow to set it to "index.html" for example, in order to immediately have the report ready in nginx server default page.
But I guess this PR can also be useful for other needs ;)
PS : It is my first golang contribution so do not hesitate to propose improvements !
> add an output-file flag to specify output file name

- internal/issues/codes.go
- internal/issues/codes_test.go
- internal/sanitize/svc.go
This PR will check that for any given Service of type LoadBalancer, if that Service has its ExternalTrafficPolicy set as "Cluster", it will call it out as an information-level message.
It is considered best practice that when using a LoadBalancer, that the services are configured as ExternalTrafficPolicy: Local, thereby reducing the possibility of additional hops inside of the Kubernetes cluster itself.  However, when the TrafficPolicy is set as Local, extra considerations must be addressed to ensure evenly-distributed traffic between nodes.
It is briefly mentioned in [this section of the docs about aws nlb.](https://kubernetes.io/docs/concepts/services-networking/service/#aws-nlb-support)
> Add an informational-level check for LB with external policy "Cluster."

- internal/issues/codes.go
- internal/issues/codes_test.go
- internal/sanitize/svc.go
This pull request adds a sanitizer for Service which checks whether any NodePort Service sets the externalTrafficPolicy to Local instead of the default value, Cluster.
`spec.externalTrafficPolicy: Local` is an option mainly used to eliminate redundant cross-node load balancing traffic when incoming traffic is already load-balanced by a load balancer outside the cluster. So, when the type of the Service is LoadBalancer, the usage of `spec.externalTrafficPolicy: Local` makes sense.
When the type of the Service is NodePort, however, specifying `spec.externalTrafficPolicy: Local` could make HTTP requests randomly fail. With NodePort Service, where all the nodes listen on the same port regardless of the inter-node distribution of Pods, even if incoming traffic reaches a node with no serving …
> Issue a warning for the usage of NodePort Service with externalTrafficPolicy:Local

- spinach/spinach_aks.yml
- spinach/spinach_eks.yml
By using the `severity:` config, I encountered that the values are actually interpreted the other way, i.e. 3 is critical, not 1.
If this is not intended, the logic needs be be adopted, since it is the current behaviour.
> Fix comment to reflect correct severity levels

- README.md
Closes https://github.com/derailed/popeye/issues/129
This should help users understand faster and in a more complete way how excludes can be used.
Changes
- Adds a paragraph of explanation for the notation needed in excludes in SpinachYAML
- Aligns the indentation under `excludes` in the YAML example (2 blanks per level)
- Extends the YAML example to include `autoscaling/v1/horizontalpodautoscalers` as an example with full group/version/resource notation.
> Add more documentation on excludes in SpinachYAML

- k8s/popeye/cronjob.yml
In the popeye:v0.3.6, image It is not accepting the s3 bucket argument in cronjob. It working fine in latest image.
> Updated the image tag in cronjob.yml

- internal/issues/codes.go
- internal/issues/codes_test.go
- internal/issues/collector.go
- internal/sanitize/node.go
Closes https://github.com/derailed/popeye/issues/136
This PR adds a check for the number of master nodes. If there is only a single one, an info is shown (severity: 1), since [multiple master nodes](https://kubernetes.io/docs/tasks/administer-cluster/highly-available-master/) are more resilient.
With one master
With 3 masters
> Add check for the number of master nodes

- assets/codes.yml
- internal/issues/codes.go
- internal/sanitize/svc.go
For the sake of resilience, it is recommendable to associate a service with more than one endpoint, so that the service can still operate while a single endpoint is not reachable.
This PR adds a check for services and emits a warning (severity 2) when a service has only one endpoint associated.
> Add check for service having multiple endpoints

- internal/issues/codes.go
- internal/issues/codes_test.go
- internal/sanitize/pod.go
- internal/sanitize/pod_test.go
A pod that is not controlled by another resource is not resilient to nodes being terminated and other common cluster disruptions. Hence this PR adds a check with severity=2 to see whether a pod is controlled by any resource.
The pod has been launched using this command:
```nohighlight
kubectl run marian-toolbox \
--namespace marian \
--stdin --tty \
--restart Never \
--rm \
--image quay.io/marian/toolbox
```
- Currently it looks as if I cannot exclude this check using this config:
```yaml
popeye:
excludes:
v1/pods:
- name: rx:marian
codes:
- 208
```
Any advice would be welcome.
> Add check for pod being controlled by other resource

- internal/sanitize/pod.go
- internal/sanitize/pod_test.go
- pkg/config/excludes.go
When individual pod containers are excluded in configuration, the remaining included containers in matching pods get scanned, but their results are not recorded because the pod name matches the name used in the configuration. The fixes in this patch remedy that situation by excluding the pods by name only when exclude configuration for that pod has zero containers specified. 
This assumes that if a user wants the pod totally excluded, no containers would be specified in the pod exclude configuration.
> fix pod reporting when some containers are excluded

- README.md
- cmd/root.go
- pkg/config/flags.go
In version 0.8.9, popeye was changed to return a non-zero exit status if the report has any errors. While this is helpful for stopping CI/CD pipelines, it broke the functionality of running popeye as a CronJob. When run as a CronJob and the report has errors, the pod results in an error state and lingers around. 
This pull request makes the non-zero exit status as an optional feature. I have added a new flag `--error-status-on-fail`. It defaults to `true`. When set to false, popeye always returns a zero exit status.
More on the issue discussed here: https://github.com/derailed/popeye/issues/122
> add a flag for switching non-zero exit status off

- README.md
--force-exit-zero It is a parameter that does not accept values, you must simply indicate --foce-exit-zero without "true"
> invalid value for --force-exit-zero

- .krew.yaml
These changes update the `.krew.yaml` file used to publish new versions of popeye to the krew-index to include artifacts for arm64 machines running macOS (Darwin). As a result of these changes, developers using Apple Silicon devices will be able to install popeye using `brew`.
Fixes #221
> 📦 Add arm64 Darwin releases to krew-index

- README.md
`go install` is an easier installation mechanism than building manually
for devs who have the golang toolchain installed.
Hence, add that to the readme.
> Add go install option to readme

- Dockerfile
This PR updates the Dockerfile to add a non-root user in docker image.
With these changes we'll be able to run `popeye` in a Kubernetes cluster with the recommended `securityContext` configuration.
Example:
```yaml
cat << EOF | kubectl apply -f -
apiVersion: batch/v1
kind: Job
metadata:
name: popeye
spec:
template:
spec:
containers:
- name: popeye
image: derailed/popeye:latest
args: [version]
securityContext:
runAsNonRoot: true    # <---------- HERE
restartPolicy: Never
backoffLimit: 0
EOF
```
Without these changes, the following error occurs:
```
Error: container has runAsNonRoot and image will run as root (pod: "popeye-qm5rm_default(38777aa3-6e21-4689-a1f7-6711bb3b0368)", container: popeye)
```
> add a non-root user in docker image

- internal/issues/assets/codes.yml
- internal/issues/codes_test.go
- internal/sanitize/pod.go
- internal/sanitize/pod_test.go
What this PR does / why we need it:
This PR adds a new check with code `209` for the sanitizer `pod.go`. In Kubernetes it is possible to have multiple `PodDisruptionBudgets` to match on one Pod via `spec.Selector.MatchLabels`. A pod should always be managed by only one PodDisruptionBudget. If a pod is managed by multiple PodDisruptionBudgets, the eviction API will disallow eviction of that pod. This leads to node drains being interrupted or blocked. For reference, [check here](https://kubernetes.io/docs/tasks/run-application/configure-pdb/#arbitrary-controllers-and-selectors). 
With this check in place, `popeye` will show an additional issue on pod sanitizers with the severity level of `Warning (2)`
Testing declaration: Some new tests were added to `pod_test.go` in order to validate the …
> Add check for pods that are managed by multiple pdbs

- docs/codes.md
- internal/issues/assets/codes.yml
- internal/sanitize/cluster.go
- internal/sanitize/cluster_test.go
- internal/scrub/cluster.go
- internal/scrub/cr.go
- internal/scrub/crb.go
- internal/scrub/hpa.go
- internal/scrub/np.go
- internal/scrub/rb.go
- internal/scrub/ro.go
- Reporting the issue `[POP-402] No metrics-server detected`
- Fix unexpected output when popeye cannot list RBAC resources
Fixes https://github.com/derailed/popeye/issues/255 
Fixes https://github.com/derailed/popeye/issues/254
As described in the following issues:
- https://github.com/derailed/popeye/issues/255 
```
go run main.go -o json | jq . | grep 402
"message": "[POP-402] No metrics-server detected"
```
- https://github.com/derailed/popeye/issues/254
```
go run main.go --kubeconfig popeye-kubeconfig.yml
```
> Reporting POP-402 issue

- Dockerfile
This PR updated the Dockerfile to fix vulnerabilities in docker base image and match go versions in build image.
I found out several vulnerabilities in docker image Alpine 3.14 and detailed results in below.
(I used trivy CLI for docker image scanning)
Support for Alpine 3.14 ended on May and there are several vulnerabilities.
So I bump Alpine from 3.14 to 3.19 to fix OS vulnerabilities.
Also modified the Dockerfile to match the go.mod file and the associated go version in build image.
trivy command:
```
trivy image derailed/popeye
```
trivy results:
```
derailed/popeye (alpine 3.14.0)
Total: 48 (UNKNOWN: 0, LOW: 0, MEDIUM: 10, HIGH: 34, CRITICAL: 4)
┌──────────────┬────────────────┬──────────┬────────┬───────────────────┬───────────────┬──────────────────────────────────────────────────── …
```
> Added vulnerability fixes for Alpine Linux OS

- .krew.yaml
I think this might fix your Krew action. Your original .krew.yaml didn't work when run through the krew-release-bot Docker container (see https://github.com/rajatjindal/krew-release-bot?tab=readme-ov-file#testing-the-template-file). The updated .krew.yaml does, you can try using:
`docker run -v $PWD/.krew.yaml:/tmp/template-file.yaml ghcr.io/rajatjindal/krew-release-bot:v0.0.46 krew-release-bot template --tag v0.20.5 --template-file /tmp/template-file.yaml`
> Krew manifest update

- Makefile
- change_logs/release_v0.21.3.md
- internal/dao/ev.go
- internal/issues/assets/codes.yaml
- internal/issues/codes_test.go
- internal/lint/cronjob.go
. [#298](https://github.com/derailed/popeye/issues/298) Popeye showing errors for Complete cronjobs (with feelings!)
> Popeye v0.21.3

- internal/db/db.go
- internal/lint/svc_test.go
- internal/lint/testdata/core/pod/4.yaml
- internal/lint/testdata/core/svc/2.yaml
Treat label selectors as an AND, not an 'at least 1' match.
Add unit test to cover case.
Fixes #302
> Fix handling of multiple label selectors in a service

- README.md
POPEYE_REPORT_DIR set the parent path for a report file. But the final path includes cluster name and context.
> Update final report path in README to avoid confusion.

- Dockerfile
- Makefile
These changes add support for building multi-platform docker images, through the `make buildx` command, and bump alpine base image version.
This is how [Kubebuilder](https://github.com/kubernetes-sigs/kubebuilder) generates the Makefile for generated-projects.
Closes: https://github.com/derailed/popeye/issues/253
I've built the image `ghcr.io/undistro/popeye:v0.11.3` with these changes. See the supported architectures:
```shell
trivy image ghcr.io/undistro/popeye:v0.11.3 
2024-02-09T11:16:34.624-0300    INFO    Vulnerability scanning is enabled
2024-02-09T11:16:34.624-0300    INFO    Secret scanning is enabled
2024-02-09T11:16:34.624-0300    INFO    If your scanning is slow, please try '--scanners vuln' to disable secret scanning
2024-02-09T11:16:34.624-0300    INFO    Please see also …
```
> Multi-platform docker image support

- .github/dependabot.yaml
Getting automated PRs is a huge help in staying on top of dependencies.
Specifically when it comes to (known) vulnerabilities; trivy currently has this to say about popeye (0.21.3):
Notice how all of these have fixes -- dependabot can provide a fix in no time!
> feat(ci): Activate dependabot

- internal/cache/cr.go
- internal/cache/cr_test.go
- internal/cache/testdata/auth/cr/1.yaml
- internal/lint/cr.go
- internal/lint/cr_test.go
- internal/lint/testdata/auth/cr/2.yaml
- spinach-examples/spinach_aks.yml
- spinach-examples/spinach_eks.yml
This PR fixes: #309 
This takes into consideration the roles that are used to generate other roles so that they are not marked as unused as per [aggregated-clusterroles](https://kubernetes.io/docs/reference/access-authn-authz/rbac/#aggregated-clusterroles)
> Add support for ClusterRule aggregationRule

- internal/cache/pod.go
- internal/lint/cm_test.go
- internal/lint/sec_test.go
- internal/lint/testdata/core/pod/1.yaml
This will now include secrets and config maps that are used in a pod via projected volumes.
fixes #365
> Add detection of projected secrets & config maps

- .goreleaser.yml
- addresses issue of not being able to install `nfpms` if you had this installed
-  https://github.com/derailed/popeye/issues/336
- based on same fix in k9s https://github.com/derailed/k9s/pull/2780
> fix path to copyright file for nfpms

- internal/lint/svc.go
currently does not consider native sidecars , and complains about target port not exist
[POP-1106] No target ports match service port
> fix linter service port check for native sidecars

- .goreleaser.yml
- Makefile
- README.md
- change_logs/release_v0.21.7.md
- cmd/info.go
- cmd/root.go
- cmd/version.go
- internal/alias.go
- internal/cilium/lint/ccnp.go
- internal/cilium/lint/cid_test.go
- internal/cilium/lint/cnp.go
- internal/cilium/lint/cnp_test.go
- internal/cilium/lint/testdata/cep/1.yaml
- internal/client/client.go
- internal/keys.go
- internal/lint/ns.go
- pkg/config/flags_test.go
- pkg/config/s3.go
- pkg/config/s3_test.go
- pkg/popeye.go
* [#414](https://github.com/derailed/popeye/issues/414) Why are there fewer inspection indicators in the new version (0.21.6)?
* [#413](https://github.com/derailed/popeye/issues/413) new version 0.21.6 is not scaning any namespace
* [#408](https://github.com/derailed/popeye/issues/408) v0.21.6 popeye -s po returns nothing and "Booms" with message "No linters matched query"
* [#388](https://github.com/derailed/popeye/issues/388) Filter by namespace intermittently includes all namespaces
> Rel v0.21.7
